from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
# Trigger reload
from pydantic import BaseModel
import httpx
import joblib
import pandas as pd
import numpy as np
import os
import xgboost
import json
from openai import OpenAI
from dotenv import load_dotenv
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

# Load environment variables 
load_dotenv()

# Configure Open Router client if the key exists
or_client = None
if os.getenv("OPENROUTER_API_KEY"):
    or_client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=os.getenv("OPENROUTER_API_KEY"),
        timeout=5.0,  # Strict 5-second killswitch for the entire HTTP session
        default_headers={
            "HTTP-Referer": "http://localhost:5173",
            "X-Title": "CropSimulator"
        }
    )

app = FastAPI(
    title="Crop Recommendation API", 
    description="XGBoost & Gemma powered crop simulation API"
)

# Setup CORS for the Vite/React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Define the global models and dataset
simulator_model = None
preprocessor = None
master_data = None
crop_max_yields = {}

# Hardcoded array of all valid crops from training
ALL_CROPS = ['BARLEY', 'CASTOR', 'CHICKPEA', 'FINGER MILLET', 'GROUNDNUT', 'LINSEED', 'MAIZE', 'PIGEONPEA', 'RAPESEED AND MUSTARD', 'RICE', 'SAFFLOWER', 'SESAMUM', 'SORGHUM', 'SUGARCANE', 'WHEAT', 'SOYABEAN', 'SUNFLOWER', 'COTTON', 'PEARL MILLET']

# Human-readable mapping for Indian local names
CROP_DISPLAY_NAMES = {
    "FINGER MILLET": "Ragi",
    "PEARL MILLET": "Bajra",
    "SORGHUM": "Jowar",
    "MAIZE": "Corn",
    "PIGEONPEA": "Tur Dal / Arhar",
    "SESAMUM": "Til",
    "LINSEED": "Flaxseed / Alsi",
    "SAFFLOWER": "Kusum",
    "RAPESEED AND MUSTARD": "Mustard / Sarson"
}

# The single source of truth for the English UI Dictionary
ENGLISH_UI_BASE = {
    "heroTag": "Live Climate Data · 2024/2025 Satellite Verified",
    "heroTitle1": "AI-Powered",
    "heroTitle2": "Crop Intelligence",
    "heroSub": "Select your state, district, and soil type. We fetch the latest climate data automatically and simulate the best crops for your land.",
    "farmProfile": "Farm Profile",
    "state": "Geographic State",
    "district": "Geographic District",
    "soil": "Primary Soil Type",
    "liveClimate": "Live Climate (2-Year Avg)",
    "fetching": "Fetching...",
    "loaded": "Loaded",
    "annual": "Annual",
    "kharif": "Kharif",
    "rabi": "Rabi",
    "noClimate": "No climate data loaded.",
    "autoFetch": "Fetched automatically from Open-Meteo · No input needed",
    "soilChem": "Soil Chemistry (kg/ha)",
    "n": "Nitrogen (N)",
    "p": "Phosphorus (P)",
    "k": "Potassium (K)",
    "runSim": "Run Yield Simulator →",
    "runningSim": "Running AI Simulation...",
    "readyTitle": "Ready to Simulate",
    "readySub": "Select your state and soil type, then click 'Run Yield Simulator' to activate the XGBoost and AI engines.",
    "aiReport": "AI Agronomist Report",
    "generatedBy": "Generated by OpenRouter LLM",
    "simResults": "Simulation Results",
    "suitability": "Suitability",
    "maxPotential": "Max Potential",
    "rank1": "Best Match",
    "rank2": "2nd Choice",
    "rank3": "3rd Choice",
    "rank4": "4th Choice",
    "rank5": "5th Choice"
}

# In-Memory Cache and Disk Cache for Translations
CACHE_DIR = "translations"
os.makedirs(CACHE_DIR, exist_ok=True)

ui_translation_cache = {
    "English": ENGLISH_UI_BASE
}

def load_cache_from_disk():
    for filename in os.listdir(CACHE_DIR):
        if filename.endswith(".json"):
            lang = filename.replace(".json", "")
            try:
                with open(os.path.join(CACHE_DIR, filename), "r", encoding="utf-8") as f:
                    ui_translation_cache[lang] = json.load(f)
            except Exception as e:
                print(f"Failed to load cache for {lang}: {e}")

load_cache_from_disk()

# Feature names required by the ML pipeline in exact order
FEATURES = [
    'N (Kg/ha)', 'P (Kg/ha)', 'K (Kg/ha)', 
    'Annual Rainfall (mm)', 'Kharif Rainfall (mm)', 'Rabi Rainfall (mm)', 
    'Irrigation Ratio', 'Primary Soil Type', 'State Name', 'Crop'
]

class PredictionRequest(BaseModel):
    n: float
    p: float
    k: float
    annual_rainfall: float
    kharif_rainfall: float
    rabi_rainfall: float
    irrigation_ratio: float
    soil_type: str
    state_name: str
    district_name: str = None
    language: str = "English"

@app.on_event("startup")
def load_ml_models():
    global simulator_model, preprocessor, master_data
    try:
        # Load the models using absolute path resolving from the main.py location
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        model_path = os.path.join(base_dir, 'models', 'tuned_simulator.joblib')
        prep_path = os.path.join(base_dir, 'models', 'simulator_preprocessor.joblib')
        data_path = os.path.join(base_dir, 'data', 'processed', 'master_dataset_clean.csv')
        
        simulator_model = joblib.load(model_path)
        preprocessor = joblib.load(prep_path)
        
        # Load dataset to serve historical defaults quickly
        master_data = pd.read_csv(data_path)
        
        # Calculate the 95th percentile (ideal) yield for every crop to use as a baseline
        global crop_max_yields
        crop_max_yields = master_data.groupby('Crop')['Yield (Kg per ha)'].quantile(0.95).to_dict()
        
        print("ML Models & Historical Data loaded successfully!")
    except Exception as e:
        print(f"Error loading ML Models: {e}")

@app.get("/")
def read_root():
    return {"status": "ok", "message": "FastAPI Yield Simulator is actively running!"}

@app.get("/api/ui-language/{language}")
def get_ui_language(language: str):
    """
    Fetches the UI translation dictionary. Uses caching to ensure we only
    ever query the LLM once per language.
    """
    if language in ui_translation_cache:
        return ui_translation_cache[language]
        
    if not or_client:
        return ENGLISH_UI_BASE # Fallback if no internet/API key
        
    print(f"Generating UI translation for {language}...")
    
    prompt = f"""
    You are an expert, highly accurate translator. Translate the following JSON values from English to {language}.
    You MUST return ONLY valid, raw JSON. Do not include markdown formatting like ```json or any conversational text. Just the raw JSON object.
    
    CRITICAL INSTRUCTION: Return the translated text in NATIVE UTF-8 characters. Absolutely DO NOT use \\uXXXX unicode escapes.
    
    {json.dumps(ENGLISH_UI_BASE)}
    """
    
    try:
        # Load the HuggingFace API key
        hf_key = os.getenv("HF_API_KEY")
        if not hf_key:
            print("No HF_API_KEY found, falling back to English.")
            return ENGLISH_UI_BASE
            
        # Using the exact LangChain implementation requested
        llm = HuggingFaceEndpoint(
            repo_id="google/gemma-4-31B-it",
            task="text-generation",
            max_new_tokens=2048,
            temperature=0.1,
            huggingfacehub_api_token=hf_key   
        )
        model = ChatHuggingFace(llm=llm)
        
        response = model.invoke(prompt)
        raw_text = response.content.strip()
        
        # Hugging Face API sometimes omits the charset header, causing `requests` to default to latin-1
        # which mangles UTF-8 text into Mojibake. This explicitly fixes it:
        try:
            raw_text = raw_text.encode('latin-1').decode('utf-8')
        except UnicodeEncodeError:
            pass # It was already decoded properly or we can't fix it
        except UnicodeDecodeError:
            pass
            
        # Clean up markdown if the LLM accidentally included it
        if raw_text.startswith("```json"):
            raw_text = raw_text.replace("```json", "", 1)
        if raw_text.startswith("```"):
            raw_text = raw_text.replace("```", "", 1)
        if raw_text.endswith("```"):
            raw_text = raw_text[:-3]
            
        # Try to fix broken unicode escapes just in case the model ignored the prompt
        raw_text = raw_text.encode('utf-8').decode('unicode_escape') if r'\u' in raw_text else raw_text
            
        translated_json = json.loads(raw_text.strip(), strict=False)
        
        # Cache it permanently to disk!
        ui_translation_cache[language] = translated_json
        with open(os.path.join(CACHE_DIR, f"{language}.json"), "w", encoding="utf-8") as f:
            json.dump(translated_json, f, ensure_ascii=False, indent=4)
            
        print(f"Successfully cached {language} UI via Hugging Face LangChain to disk!")
        return translated_json
        
    except Exception as e:
        print(f"Hugging Face Translation failed: {e}")
        return ENGLISH_UI_BASE



@app.get("/api/districts/{state_name}")
def get_state_districts(state_name: str):
    if master_data is None:
        raise HTTPException(status_code=500, detail="Database not loaded")
        
    search_state = state_name
    if search_state.upper() == "ODISHA":
        search_state = "Orissa"
        
    state_data = master_data[master_data['State Name'].str.upper() == search_state.upper()]
    if state_data.empty:
        return []
        
    districts = state_data['Dist Name'].dropna().unique().tolist()
    districts.sort()
    return districts


@app.get("/api/defaults/{state_name}")
def get_state_defaults(state_name: str, district: str = None):
    if master_data is None:
        raise HTTPException(status_code=500, detail="Database not loaded")
        
    # Map modern state names to historical dataset spelling
    search_state = state_name
    if search_state.upper() == "ODISHA":
        search_state = "Orissa"
        
    state_data = master_data[master_data['State Name'].str.upper() == search_state.upper()]
    
    if state_data.empty:
        raise HTTPException(status_code=404, detail="State not found")
        
    # Filter down to district if requested, else use state data
    dist_data = state_data
    if district:
        filtered = state_data[state_data['Dist Name'].str.upper() == district.upper()]
        if not filtered.empty:
            dist_data = filtered

    # Default to 50-year historical averages
    annual_rain = round(dist_data['Annual Rainfall (mm)'].mean(), 1)
    kharif_rain = round(dist_data['Kharif Rainfall (mm)'].mean(), 1)
    rabi_rain = round(dist_data['Rabi Rainfall (mm)'].mean(), 1)
    
    # Attempt to fetch LIVE weather data from Open-Meteo API (2-year average: 2024 + 2025)
    try:
        # 1. Get Lat/Lon of State or District
        query = f"{district},{state_name}+India" if district else f"{state_name}+India"
        geo_res = httpx.get(f"https://nominatim.openstreetmap.org/search?q={query}&format=json", headers={'User-Agent': 'CropRecommendationSystem/1.0'}, timeout=3.0)
        if geo_res.status_code == 200 and len(geo_res.json()) > 0:
            lat = geo_res.json()[0]['lat']
            lon = geo_res.json()[0]['lon']
            
            # 2. Fetch 10-Year historical data block (2015-2024)
            weather_res = httpx.get(
                f"https://archive-api.open-meteo.com/v1/archive?latitude={lat}&longitude={lon}&start_date=2015-01-01&end_date=2024-12-31&daily=precipitation_sum&timezone=auto",
                timeout=10.0
            )
            if weather_res.status_code == 200:
                data = weather_res.json()
                dates = data['daily']['time']
                precip = data['daily']['precipitation_sum']
                
                # Accumulators for 10 years
                yearly = {y: {"annual": 0, "kharif": 0, "rabi": 0} for y in range(2015, 2025)}
                
                for d, p in zip(dates, precip):
                    if p is None: continue
                    year = int(d.split('-')[0])
                    month = int(d.split('-')[1])
                    if year not in yearly: continue
                    yearly[year]["annual"] += p
                    if 6 <= month <= 9:
                        yearly[year]["kharif"] += p
                    elif month >= 10 or month <= 3:
                        yearly[year]["rabi"] += p

                # Average the 10 years for a highly statistically reliable baseline
                annual_rain = round(sum(yearly[y]["annual"] for y in range(2015, 2025)) / 10, 1)
                kharif_rain = round(sum(yearly[y]["kharif"] for y in range(2015, 2025)) / 10, 1)
                rabi_rain   = round(sum(yearly[y]["rabi"]   for y in range(2015, 2025)) / 10, 1)
                
                location_msg = f"{district}, {state_name}" if district else state_name
                print(f"Successfully fetched 10-year averaged weather for {location_msg} (2015-2024)")
    except Exception as e:
        print(f"Live Weather API Failed. Falling back to 50-year historical average: {e}")
        
    return {
        "state": state_name.upper(),
        "district": district.upper() if district else None,
        "n_avg": round(dist_data['N (Kg/ha)'].mean(), 1),
        "p_avg": round(dist_data['P (Kg/ha)'].mean(), 1),
        "k_avg": round(dist_data['K (Kg/ha)'].mean(), 1),
        "annual_rainfall_avg": annual_rain,
        "kharif_rainfall_avg": kharif_rain,
        "rabi_rainfall_avg": rabi_rain,
        "irrigation_ratio_avg": round(dist_data['Irrigation Ratio'].mean(), 3)
    }

@app.post("/api/simulate")
def simulate_yield(request: PredictionRequest):
    if not simulator_model or not preprocessor:
        raise HTTPException(status_code=500, detail="ML Models are not loaded")
        
    try:
        # Map modern state names to historical dataset spelling
        ml_state_name = request.state_name
        if ml_state_name.upper() == "ODISHA":
            ml_state_name = "Orissa"

        # Create the environment profile based on user input
        env_profile = {
            'N (Kg/ha)': request.n,
            'P (Kg/ha)': request.p,
            'K (Kg/ha)': request.k,
            'Annual Rainfall (mm)': request.annual_rainfall,
            'Kharif Rainfall (mm)': request.kharif_rainfall,
            'Rabi Rainfall (mm)': request.rabi_rainfall,
            'Irrigation Ratio': request.irrigation_ratio,
            'Primary Soil Type': request.soil_type,
            'State Name': ml_state_name
        }
        
        # 1. Artificially duplicate this environment 19 times
        env_df = pd.DataFrame([env_profile] * len(ALL_CROPS))
        
        # 2. Assign the 19 unique crop names
        env_df['Crop'] = ALL_CROPS
        
        # Ensure column order matches the training features
        env_df = env_df[FEATURES]
        
        # 3. Process data
        X_processed = preprocessor.transform(env_df)
        
        # 4. Predict Yields for all 19 crops
        simulated_yields = simulator_model.predict(X_processed)
        
        # 5. Calculate "Suitability Score" (%) and Sort Top 3
        # We divide the predicted yield by the crop's 95th percentile historical max.
        # This prevents extremely heavy crops (like Sugarcane) from always winning.
        results = []
        for crop, yield_val in zip(ALL_CROPS, simulated_yields):
            baseline_max = crop_max_yields.get(crop, yield_val)
            suitability_score = (yield_val / baseline_max) * 100
            
            # Cap at 100% just for display cleanliness if it exceeds historical max
            suitability_score = min(suitability_score, 100.0) 
            
            # Map to local Indian name, or just Title Case the original
            display_name = CROP_DISPLAY_NAMES.get(crop, crop.title())
            
            results.append((display_name, float(yield_val), float(suitability_score), float(baseline_max)))
            
        # Sort by Suitability Score FIRST (x[2]). 
        # If there is a tie (multiple crops at 100%), break the tie using Raw Yield (x[1])!
        results.sort(key=lambda x: (x[2], x[1]), reverse=True)
        
        top_5 = results[:5]
        
        # Format the response
        recommendations = [
            {
                "crop": crop, 
                "expected_yield_kg_per_ha": round(yield_val, 1),
                "max_potential_yield": round(baseline_max, 1),
                "suitability_percentage": round(score, 1)
            } 
            for crop, yield_val, score, baseline_max in top_5
        ]
        
        # 6. Generate the AI Agronomist Report using Open Router
        ai_report = "AI Advisory is unavailable. Please check your OPENROUTER_API_KEY in the .env file."
        if or_client:
            # Open Router allows access to models like deepseek/deepseek-chat
            loc_str = f"{request.district_name} district, {request.state_name}" if request.district_name else request.state_name
            prompt = f"""
            You are an expert Indian Agronomist speaking directly to a farmer in {loc_str} with {request.soil_type} soil.
            Their soil nutrients are: N={request.n}, P={request.p}, K={request.k}.
            Their historical annual rainfall is {request.annual_rainfall} mm. 
            
            Our AI Simulation Engine has mathematically determined their Top 5 best crops:
            1. {top_5[0][0]} (Suitability: {top_5[0][2]:.1f}%)
            2. {top_5[1][0]} (Suitability: {top_5[1][2]:.1f}%)
            3. {top_5[2][0]} (Suitability: {top_5[2][2]:.1f}%)
            4. {top_5[3][0]} (Suitability: {top_5[3][2]:.1f}%)
            5. {top_5[4][0]} (Suitability: {top_5[4][2]:.1f}%)
            
            Write a short, punchy 3-paragraph advisory in extremely simple, plain language that a local farmer can easily understand. 
            Paragraph 1: Explain why the top crop is an excellent choice for their region and soil. Crucially, explicitly name a specific local variety of that crop that thrives in their exact district (e.g. if Rice in Haryana, recommend Basmati; if Rice in Andhra, recommend Sona Masoori).
            Paragraph 2: Give one quick, practical tip about fertilizer based on their NPK values.
            
            CRITICAL RULES:
            - You MUST write your entire response exclusively in {request.language}.
            - Use basic, conversational language. Absolutely NO complex scientific jargon or academic language.
            - NEVER output exact rainfall numbers (mm) to the farmer. Translate the data into plain words (e.g. "heavy monsoon region" or "drier climate").
            - Keep it concise (maximum 4-5 sentences total).
            - Do not use asterisks or bolding.
            """
            # Waterfall Fallback System: If a model hits a rate limit or queue, try the next!
            models_to_try = [
                "openai/gpt-oss-120b:free",           # User's primary choice
                "meta-llama/llama-3.2-3b-instruct:free", # Highly reliable backup
                "minimax/minimax-m2.5:free"            # Fast 3rd tier backup
            ]
            
            ai_report_generated = None
            
            for model_id in models_to_try:
                try:
                    response = or_client.chat.completions.create(
                        model=model_id, 
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.5,
                        max_tokens=250
                    )
                    ai_report_generated = response.choices[0].message.content
                    print(f"Successfully generated AI report using: {model_id}")
                    break # Success! Break out of the loop
                except Exception as e:
                    print(f"Open Router Model {model_id} failed: {e}. Trying next...")
            
            if ai_report_generated:
                ai_report = ai_report_generated
            else:
                ai_report = "AI Advisory is temporarily unavailable. All 3 backup models hit rate limits or timed out."

        return {
            "status": "success",
            "state_simulated": request.state_name,
            "recommendations": recommendations,
            "ai_advisory": ai_report
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Simulation error: {str(e)}")
